- src/project/test/context.rs
When Typst is missing, the error should indicate that, instead of generically saying a file is missing.
My approach involves creating a custom `ErrorImpl::MissingTypst` variant based on the kind of the I/O error, but, if you prefer, we can also just use the existing `ErrorImpl::Io` variant and check for its `kind()` upon `Display`.
(I've confirmed that my approach does not give a false positive when running `typst invalid-file.typ`; it fails in a different way which is properly picked up by the test failure system.)
⚠️ **Make sure to confirm, before merging,** if this approach (of checking `kind()`) works on Windows as well, as it's an OS-related error (I've only tested on my Linux PC).
**Before:**
```
Error: compilation stage failed while executing typst
Caused by:
No such file or …
```
> Add special error for missing Typst executable

- Cargo.lock
- docs/book/src/README.md
- docs/book/src/quickstart/install.md
- docs/book/src/quickstart/usage.md
> Update dependencies & Fix some book entries

- Justfile
- just/check.just
- just/doc.just
- just/test.just
> Improve Justfile

- README.md
- crates/typst-test-cli/src/cli.rs
- crates/typst-test-cli/src/cli/add.rs
- crates/typst-test-cli/src/project.rs
- crates/typst-test-cli/src/report.rs
- crates/typst-test-cli/src/test/runner.rs
- crates/typst-test-lib/src/compare.rs
- crates/typst-test-lib/src/hook.rs
- crates/typst-test-lib/src/library.rs
- crates/typst-test-lib/src/store.rs
- crates/typst-test-lib/src/store/page.rs
- crates/typst-test-lib/src/store/project/v1.rs
- crates/typst-test-lib/src/store/test.rs
- crates/typst-test-lib/src/store/test/collector.rs
- crates/typst-test-lib/src/store/vcs.rs
- crates/typst-test-lib/src/test.rs
- crates/typst-test-lib/src/test/id.rs
- crates/typst-test-lib/src/test_set.rs
- crates/typst-test-lib/src/test_set/eval.rs
- crates/typst-test-lib/src/test_set/id.rs
- crates/typst-test-lib/src/test_set/parsing.rs
- docs/book/src/README.md
- migrating.md
> Fix various typos

- .github/workflows/ci.yml
> Add 1.79 MSRV check to CI

- .github/workflows/gh-pages.yml
- Justfile
- docs/book/.gitignore
- docs/book/book.toml
> Update book setup

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> Add contribution docs and templates

- crates/typst-test-cli/src/cli/mod.rs
- crates/typst-test-cli/src/cli/run.rs
- crates/typst-test-cli/src/cli/update.rs
- crates/typst-test-cli/src/runner.rs
> Allow promoting warnings to errors

- crates/typst-test-cli/src/cli/mod.rs
- crates/typst-test-cli/src/cli/util/about.rs
- crates/typst-test-cli/src/cli/util/mod.rs
> Add a `--version` flag and `util about` sub command

- Justfile
- flake.lock
- flake.nix
> nix: Add a flake

- crates/typst-test-cli/src/cli/mod.rs
- crates/typst-test-cli/src/cli/util/fonts.rs
- crates/typst-test-cli/src/cli/util/migrate.rs
- crates/typst-test-cli/src/cli/util/mod.rs
- crates/typst-test-lib/src/test/id.rs
- crates/typst-test-lib/src/test/suite.rs
> feat: Don't collect nested tests

- crates/typst-test-lib/src/test/suite.rs
- crates/typst-test-lib/src/test_set/eval/func.rs
- crates/typst-test-lib/src/test_set/eval/mod.rs
- crates/typst-test-lib/src/test_set/eval/set.rs
- crates/typst-test-lib/src/test_set/eval/value.rs
- crates/typst-test-lib/src/test_set/glob.rs
- crates/typst-test-lib/src/test_set/id.rs
- crates/typst-test-lib/src/test_set/mod.rs
- crates/typst-test-lib/src/test_set/num.rs
- crates/typst-test-lib/src/test_set/parse.rs
- crates/typst-test-lib/src/test_set/pat.rs
- crates/typst-test-lib/src/test_set/regex.rs
- crates/typst-test-lib/src/test_set/str.rs
- crates/typst-test/src/cli/mod.rs
- crates/typst-test/src/cli/remove.rs
- crates/typst-test/src/cli/uninit.rs
- crates/typst-test/src/cli/update.rs
> lib: Stabilize a subset of the test_set API

- crates/typst-test/src/cli/mod.rs
> fix: Make `--now` arg actually a flag

- crates/tytanic/Cargo.toml
- docs/book/src/quickstart/install.md
> crates: Add binstall templates

- crates/tytanic/src/cli/status.rs
> cli: status: Show if regression test template is found

- CHANGELOG.md
- crates/tytanic/src/cli/add.rs
> cli: add: Properly report diagnostics for faulty template

- CHANGELOG.md
- crates/tytanic-core/src/doc/mod.rs
- crates/tytanic/src/runner.rs
> cli: Ensure `--no-fail-fast` is respected

- CHANGELOG.md
- crates/tytanic/src/cli/add.rs
> cli: add: Don't add references for non-pereistent tests

- CHANGELOG.md
- crates/tytanic/src/cli/add.rs
- crates/tytanic/src/cli/list.rs
- crates/tytanic/src/cli/mod.rs
- crates/tytanic/src/cli/options.rs
- crates/tytanic/src/cli/remove.rs
- crates/tytanic/src/cli/run.rs
- crates/tytanic/src/cli/update.rs
- crates/tytanic/src/cli/util/fonts.rs
- crates/tytanic/src/kit.rs
- crates/tytanic/src/main.rs
- crates/tytanic/src/runner.rs
This mainly concerns consistency across multiple commands and switches which turn features on or off, see commit messages for more details.
> cli: Refactor CLI options

- CHANGELOG.md
- crates/tytanic-core/src/test/annotation.rs
- crates/tytanic-core/src/test/mod.rs
- docs/book/src/reference/tests/annotations.md
> test: Fix annotation parsing

- CHANGELOG.md
- crates/tytanic-core/src/test/suite.rs
- crates/tytanic/src/cli/mod.rs
- crates/tytanic/src/cli/util/migrate.rs
> test: Don't force migration

- .dockerignore
- .github/workflows/docker.yml
- Dockerfile
- Justfile
> docker: Add a Dockerfile and release action 

- CHANGELOG.md
- crates/tytanic-core/src/doc/compile.rs
- crates/tytanic-core/src/doc/mod.rs
- crates/tytanic-core/src/library.rs
- crates/tytanic/src/cli/new.rs
- crates/tytanic/src/cli/options.rs
- crates/tytanic/src/cli/run.rs
- crates/tytanic/src/cli/update.rs
- crates/tytanic/src/report.rs
- crates/tytanic/src/runner.rs
> runner: Don't ignore warnings

- crates/tytanic-core/src/project/mod.rs
- crates/tytanic-core/src/project/vcs.rs
- crates/tytanic/src/cli/status.rs
- crates/tytanic/src/json.rs
> fs: Ignore invalid manifests where possible.

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/tytanic-core/Cargo.toml
- crates/tytanic-core/src/_dev.rs
- crates/tytanic-core/src/doc/compile.rs
- crates/tytanic-core/src/lib.rs
- crates/tytanic-core/src/library.rs
- crates/tytanic-filter/Cargo.toml
- crates/tytanic-utils/Cargo.toml
- crates/tytanic-utils/src/lib.rs
- crates/tytanic/Cargo.toml
- docs/book/src/quickstart/install.md
> release: v0.1.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/tytanic-core/src/test/mod.rs
- docs/book/src/quickstart/install.md
> release: v0.1.3

- CHANGELOG.md
- crates/tytanic/Cargo.toml
- crates/tytanic/src/cli/commands/mod.rs
- crates/tytanic/src/cli/commands/new.rs
- crates/tytanic/src/cli/commands/run.rs
- crates/tytanic/src/cli/commands/update.rs
- crates/tytanic/src/cli/commands/util/fonts.rs
- crates/tytanic/src/cli/mod.rs
- crates/tytanic/src/kit.rs
- crates/tytanic/src/main.rs
- crates/tytanic/src/world.rs
> cli: Improve reproducibility

- crates/tytanic-core/src/suite.rs
- crates/tytanic/src/report.rs
> ui: Fix status output coloring

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- assets/workflows/tests.yml
- docs/architecture.md
- docs/book/src/guides/ci.md
> chore: Cleanup & docs

- CHANGELOG.md
- Cargo.lock
- README.md
- crates/tytanic-core/src/config.rs
- crates/tytanic-core/src/project/mod.rs
- crates/tytanic-core/src/project/vcs.rs
- crates/tytanic-core/src/suite.rs
- crates/tytanic-core/src/test/mod.rs
- crates/tytanic-utils/Cargo.toml
- crates/tytanic-utils/src/lib.rs
- crates/tytanic-utils/src/typst.rs
- crates/tytanic/src/cli/commands/delete.rs
- crates/tytanic/src/cli/commands/mod.rs
- crates/tytanic/src/cli/commands/new.rs
- crates/tytanic/src/cli/commands/status.rs
- crates/tytanic/src/cli/commands/util/clean.rs
- crates/tytanic/src/cli/commands/util/migrate.rs
- crates/tytanic/src/cli/commands/util/vcs.rs
- crates/tytanic/src/cli/mod.rs
- crates/tytanic/src/main.rs
- crates/tytanic/src/report.rs
- crates/tytanic/src/runner.rs
- docs/book/src/README.md
- docs/book/src/SUMMARY.md
- docs/book/src/guides/tests.md
- docs/book/src/reference/config.md
- docs/book/src/reference/tests/README.md
- docs/book/src/reference/tests/unit.md
> config: Add `tool.tytanic.test` for configuring unit test root

- crates/tytanic-core/src/test/mod.rs
- crates/tytanic/src/cli/commands/list.rs
- crates/tytanic/src/cli/commands/run.rs
- crates/tytanic/src/cli/commands/update.rs
- crates/tytanic/src/json.rs
- crates/tytanic/src/report.rs
- crates/tytanic/src/runner.rs
- crates/tytanic/src/ui.rs
> ui: Improvements to test listing and live reporting

- Justfile
- flake.nix
> project: Improve development

- crates/tytanic-core/src/dsl.rs
> filter: Register correct compile-only test set

- CHANGELOG.md
- crates/tytanic-core/src/config.rs
- crates/tytanic-core/src/project/mod.rs
- crates/tytanic-core/src/test/annotation.rs
- crates/tytanic-core/src/test/mod.rs
- crates/tytanic/src/cli/commands/mod.rs
- crates/tytanic/src/cli/commands/new.rs
- crates/tytanic/src/cli/commands/run.rs
- crates/tytanic/src/cli/commands/update.rs
- crates/tytanic/src/runner.rs
- docs/book/src/reference/tests/annotations.md
> config: Allow configuring defaults per test and per project

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
> github: Disable blank issues

- crates/tytanic/src/cli/mod.rs
- crates/tytanic/src/main.rs
> ui: Handle more errors gracefully

- docs/book/src/quickstart/usage.md
Fixes the broken link at the end of https://tingerrr.github.io/tytanic/quickstart/usage.html
> docs: fix broken link

- .github/ISSUE_TEMPLATE/config.yml
> github: Allow blank issues

- crates/tytanic/src/cli/commands/update.rs
- docs/CHANGELOG.md
> cli: update: Don't include non-persistent tests

- crates/tytanic-core/src/suite.rs
> ui: Improve tracing coverage

- crates/tytanic-core/src/suite.rs
Reverts tingerrr/tytanic#146
whoops
> Revert "ui: Improve tracing coverage"

- crates/tytanic-core/src/doc/compile.rs
- crates/tytanic-core/src/doc/mod.rs
- crates/tytanic-core/src/library.rs
- crates/tytanic/src/cli/commands/new.rs
- crates/tytanic/src/runner.rs
- docs/book/src/reference/tests/template.md
> core: Use correct root for template tests

- crates/tytanic-core/src/doc/mod.rs
- crates/tytanic-core/src/project/mod.rs
- crates/tytanic-core/src/project/vcs.rs
- crates/tytanic-core/src/suite.rs
- crates/tytanic-core/src/test/template.rs
- crates/tytanic-core/src/test/unit.rs
- crates/tytanic-filter/src/eval/mod.rs
- crates/tytanic/src/cli/mod.rs
- crates/tytanic/src/kit.rs
- crates/tytanic/src/runner.rs
- crates/tytanic/src/world.rs
> tracing: Improve tracing coverage

- crates/tytanic/src/cli/commands/list.rs
- crates/tytanic/src/json.rs
- docs/CHANGELOG.md
> cli: Add test paths to JSON output

- Cargo.lock
> deps: Bump dependencies

- assets/workflows/ci.yml
- docs/book/src/guides/ci.md
> docs: Update stale versions and GH actions

- Cargo.lock
- Cargo.toml
- crates/tytanic/Cargo.toml
- crates/tytanic/src/cli/commands/util/completion.rs
- crates/tytanic/src/cli/commands/util/mod.rs
> cli: Add completions

- Cargo.lock
- Cargo.toml
- crates/tytanic/Cargo.toml
- crates/tytanic/src/cli/commands/util/manpage.rs
- crates/tytanic/src/cli/commands/util/mod.rs
> cli: Add manpage generation

- crates/tytanic-core/src/test/unit.rs
- crates/tytanic/src/cli/commands/run.rs
- crates/tytanic/src/cli/commands/update.rs
- crates/tytanic/src/runner.rs
> core/runner: Don't create unnecessary temporary directories

- crates/tytanic-core/src/suite.rs
> collector: Ignore invalid identifiers

- crates/tytanic/src/cli/commands/util/clean.rs
- crates/tytanic/src/cli/commands/util/mod.rs
- docs/CHANGELOG.md
> cli: util clean: Add filter options

- docs/CONTRIBUTING.md
> docs: Clean up CONTRIBUTING.md

- crates/tytanic-filter/src/ast/grammar.pest
- crates/tytanic-filter/src/ast/mod.rs
- crates/tytanic-filter/src/ast/parser.rs
- docs/CHANGELOG.md
- docs/book/src/guides/test-sets.md
- docs/book/src/reference/test-sets/grammar.md
> filter: Allow more delimiters in testset raw patterns

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/tracking_issue.md
> Use issue types and add tracking issue template

- crates/tytanic-core/src/project/vcs.rs
- docs/CHANGELOG.md
> core: Add sapling as git-compatible VCS

- docs/CHANGELOG.md
https://bmitch.net/blog/2025-08-22-ghrc-appears-malicious/
> Replace malicious container registry references with ghcr
